#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

  [0] = LAYOUT(
      KC_NO, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_NO,
      KC_NO, CTL_T(KC_A), KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, CTL_T(KC_SCLN), KC_NO,
      KC_NO, SFT_T(KC_Z), KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, SFT_T(KC_SLSH), KC_NO,
      LT(2, KC_SPC), KC_LCTL, KC_ENT, MO(1)
  ),

  [1] = LAYOUT(
      KC_NO, KC_NO, KC_1, KC_2, KC_3, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
      KC_NO, QK_GESC, KC_4, KC_5, KC_6, KC_0, KC_LEFT, KC_DOWN, KC_UP, KC_RIGHT, KC_BSPC, KC_NO,
      KC_NO, KC_LSFT, KC_7, KC_8, KC_9, KC_NO, CG_TOGG, KC_NO, KC_NO, KC_NO, KC_RSFT, KC_NO,
      MO(4), KC_LCTL, KC_ENT, KC_NO
  ),

  [2] = LAYOUT(
      KC_NO, QK_GESC, KC_NO, KC_NO, KC_NO, KC_NO, KC_GRAVE, KC_MINS, KC_EQL, KC_NO, KC_NO, KC_NO,
      KC_NO, KC_LCTL, KC_TAB, KC_NO, KC_NO, KC_NO, KC_NO, KC_LBRC, KC_RBRC, KC_NO, KC_QUOT, KC_NO,
      KC_NO, KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LPRN, KC_RPRN, KC_NO, KC_BSLS, KC_NO,
      KC_NO, KC_LCTL, KC_ENT, MO(3)
  ),

  [3] = LAYOUT(
      KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PGDN, KC_PGUP, KC_NO, KC_NO, KC_NO,
      KC_NO, KC_NO, KC_NO, KC_MS_BTN2, KC_MS_BTN1, KC_NO, KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R, KC_NO, KC_NO,
      KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
      KC_NO, KC_LCTL, KC_ENT, KC_NO
  ),

  [4] = LAYOUT(
      KC_NO, KC_NO, KC_F1, KC_F2, KC_F3, KC_F10, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
      KC_NO, KC_LCTL, KC_F4, KC_F5, KC_F6, KC_F11, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
      KC_NO, KC_LSFT, KC_F7, KC_F8, KC_F9, KC_F12, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
      KC_NO, KC_LCTL, KC_ENT, KC_NO
  )
};
